### ISSUE TITLE
Top-level preambles are imported from other .lf files

### ISSUE THREAD

**Issue by Soroosh129** [icyphy/lingua-franca#267] opened 2021-01-22 01:05 UTC
There is an interesting quirk to the import system in that it imports the top-level preamble from an external `.lf` file if any reactor is imported from that file.

Here is a working example: in generated code for [`RhythmLinux.lf`](https://github.com/icyphy/lingua-franca/blob/master/example/Rhythm/RhythmLinux.lf), the top-level preamble from [`RhythmMac.lf`](https://github.com/icyphy/lingua-franca/blob/master/example/Rhythm/RhythmMac.lf) is automatically included. Adding a top-level preamble to `RhythmLinux.lf` will cause both preambles to be added at the beginning of the generated `RhythmLinux.c`.

**Comment by lhstrh** [comment] 2021-01-22 04:06
This is not a bug but a feature. This has to happen in case imported reactors depend on the code in the preamble of the file in which they are defined. There are clearly also limitations to this, mostly because we clunk everything in one file, which then likely also creates conflicts. To resolve this, much bigger changes are needed, which we tend to discuss periodically but never address because implementing a proper solution is "just more work" and doesn't really serve immediate research goals. Stepping away from a single-file compilation process has so far been met with some resistance, because it makes things more complex, but I don't see how we can grow to larger applications without doing this. The question is: how long are we willing to kick the can down the road?

**Comment by edwardalee** [comment] 2021-01-22 13:13
I think that rather than RhythmLinux inheriting from RhythmMac, they should both inherit from a RhythmBase.

**Comment by Soroosh129** [comment] 2021-01-22 18:04
As an alternative, if both `audio_loop_mac.c` and `audio_loop_linux.c` were in the `files` list, we could have a unified Rhythm example. They both can include `audio_loop.h`. I have also added a directive to the top-level preamble of `RhythmMac.lf` that chooses an audio interface implementation based on the platform.

@lhstrh I think in this case a simple solution such as being able to explicitly import the preamble from a file might also work. I'm all for supporting separate files but I don't know if it would help the Rhythm example.

**Comment by cmnrd** [comment] 2021-09-17 07:07
Should we declare this a feature and close the issue?

**Comment by edwardalee** [comment] 2021-09-18 23:33
Yes, this is a feature.

**Closed by edwardalee** 2021-09-18 23:33 UTC
Labels: bug
