### ISSUE TITLE
Gradle build only works for specific Java versions

### ISSUE THREAD

**Issue by mew2ub** [icyphy/lingua-franca#125] opened 2020-03-24 19:42 UTC
I ran this problem for the second time so I thought I'd document it in an issue. I was unable to use run-lf-tests on my mac's command line because I was getting a build error:

```
Matts-MacBook-Pro-3:lingua-franca matt.weber$ bin/run-lf-tests C
Jar file is missing or out-of-date; running Gradle...

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/matt.weber/git/lingua-franca/xtext/org.icyphy.linguafranca/build.gradle'

* What went wrong:
Could not compile build file '/Users/matt.weber/git/lingua-franca/xtext/org.icyphy.linguafranca/build.gradle'.
> startup failed:
  General error during semantic analysis: Unsupported class file major version 57

...
```

The problem seems to be that I was using Java 13.

```
Matts-MacBook-Pro-3:lingua-franca matt.weber$ java --version
java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

because the build error went away when I changed to Java 11 via the command

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-11.0.6.jdk/Contents/Home
```

I think we should either fix the build error for all Java versions or give instructions on how to change Java versions.

**Comment by lhstrh** [comment] 2020-06-23 04:43
Changing Java versions varies from platform to platform, so I'm not sure that providing instructions will be all that helpful (e.g., some Linux distributions have dedicated commands to switch). However, we should state clearly which versions of Java we support. Have you only ran into problems with Java 13, or are there other versions that you've had issue with? It is a known issue that older versions of Gradle don't work well with newer versions of Java; I'll just go ahead and upgrade the version we ship with the code. After that, let's verify that versions > 8 work correctly.

**Comment by mew2ub** [comment] 2020-06-23 18:13
I think it was just Java 13.

I was thinking the instructions would either be platform specific or very general like "set JAVA_HOME home to the correct path for your platform"

**Comment by lhstrh** [comment] 2020-06-23 21:11
I've updated our configuration to use Gradle 6.5 along with more up-to-date libraries and was able to build with Java 13 without problems. I'll push the update configuration shortly.

**Comment by lsk567** [comment] 2020-06-23 21:35
> I've updated our configuration to use Gradle 6.5 along with more up-to-date libraries and was able to build with Java 13 without problems. I'll push the update configuration shortly.

This fix also helps with installing LF on Catalina, since Catalina only runs JVM 14 (older JVMs are disallowed in its hardened runtime) and it is only compatible with Gradle 6+.

**Comment by lhstrh** [comment] 2020-06-23 23:07
See https://github.com/icyphy/lingua-franca/commit/51d15a18b067ac57c3ffdd9bdf5b84901f73c1ac.

Running the test suite in an existing configuration might initially fail, in which case running `build-lfc -c` should clean the configuration and pull in all updates...

**Comment by lhstrh** [comment] 2020-06-23 23:21
I can confirm that compilation now also works with Java 14. @lsk567: what remaining steps are necessary to things to work on Catalina?

**Comment by lhstrh** [comment] 2020-06-23 23:48
Closing this. @lsk567: please create a new issue regarding Catalina.

**Closed by lhstrh** 2020-06-23 23:48 UTC
Labels: bug

**Comment by lsk567** [comment] 2020-06-24 00:18
@lhstrh With the new Gradle update, Java 14 becomes the only prerequisite to run the LF IDE on Catalina. I will create a separate issue to document this problem.

**Comment by lhstrh** [comment] 2020-06-24 00:54
Oh, that's great news! We can just document this requirement on the wiki.
I'm assuming that you have been able to get it running on your machine?
