### ISSUE TITLE
Travis ran out of OSS credits

### ISSUE THREAD

**Issue by Soroosh129** [icyphy/lingua-franca#231] opened 2020-11-05 23:02 UTC
It seems like we ran out of credits after a few days.

Currently, we have a non-working CI situation. I suggest we should contact Travis's support and acquire some OSS credits, or decide to stick to GitHub's built-in CI. In either case this is an urgent matter.

**Comment by edwardalee** [comment] 2020-11-06 01:24
I can sign us up for a plan, but which one? Do we need 5 concurrent jobs?  I guess we are running Ptolemy builds as well as Lingua Franca.

**Comment by cxbrooks** [comment] 2020-11-06 01:49
I changed the ptII Travis cron job to monthly, I think it was daily before.  Perhaps the ptII job should move to a different group, but the issue is that the ptII repo is in the icyphy group on github.  I'm guessing that Travis would be wise to us trying to split up the jobs in to multiple groups.  The Kepler was also being run weekly, I changed it to monthly.   I would like to see the ptII and Kepler repos continue to build.

**Comment by Soroosh129** [comment] 2020-11-06 02:36
In light of Ptolemy II daily test runs being converted to monthly, I think the 1 concurrent job plan should be sufficient for our needs. It would just take longer for our tests to finish.

**Comment by cmnrd** [comment] 2020-11-06 08:17
I could try to migrate our CI to GitHub Actions if that is wanted

**Comment by lhstrh** [comment] 2020-11-06 19:35
Travis says:

> 0 available credits (next replenish date: November 06, 2020) 

So we'll be able to build again tomorrow, even if we don't upgrade.

With regard to concurrent builds: don't we also just have 1 concurrent build under the OSS Free plan? This would still allow us to execute subtasks concurrently as we do now, I believe. If this is the case, I agree with @Soroosh129 that this suffices.

I think it's a good idea to explore GitHub Actions, but I don't consider it a very high priority. @cmnrd: is it possible to set this up in parallel? That would allow us to compare and make a smooth transition, if desired...

**Comment by lhstrh** [comment] 2020-11-08 02:08
Not sure what is going on. When I looked today, Travis said:

> 0 available credits (next replenish date: November 07, 2020) 

Probably has something to do with our negative balance.

I've spend some time getting Github Actions to work, and we're pretty close. Some extra work is needed, for example, to support macOS because the way will pull in submodules is only supported by Linux at the moment.

**Comment by lhstrh** [comment] 2020-11-10 00:33
Looks like Github Actions is humming along. Closing this for now as it seems to adequately address our need to have CI for pushes and PRs.

@cxbrooks: If you're wondering why your builds are not happening, this is because we're still at -4890 credits. Not sure when we can expect this to jump back to +5110.

**Closed by lhstrh** 2020-11-10 00:33 UTC
