### ISSUE TITLE
junit tests do not run in Eclipse with the Oomph setup

### ISSUE THREAD

**Issue by edwardalee** [icyphy/lingua-franca#284] opened 2021-03-03 01:35 UTC
Our junit tests do not run in Eclipse with the Oomph setup.  To reproduce, go to `LinguaFrancaValidationTest.xtend`, select any test, right click and choose `Run as junit test`. The error message is:
```
java.lang.NoClassDefFoundError: org/junit/platform/commons/util/ClassNamePatternFilterUtils
```
Googling around, `ClassNamePatternFilterUtils` seems to be something in some more recent version of junit.  The Oomph setup file makes no mention of junit, so I'm not sure how to fix this. Suggestions?

**Comment by lhstrh** [comment] 2021-03-05 07:22
@a-sr Any idea? @edwardalee could you try to right-click on the project -> Gradle -> Refresh Gradle Project and see whether this fixes it? I've noticed that since the project configuration is "Gradle aware", dependencies from the Gradle configuration are ignored until  you manually do this "refresh" step. I don't understand the reasoning behind this, but that's what I end up having to do a lot since those Oomph-generated Eclipse config files were committed to the repo...

**Comment by edwardalee** [comment] 2021-03-07 22:09
Refresh Gradle Project had no effect.  I still get the same error when trying to run a JUnit test.

**Comment by a-sr** [comment] 2021-03-13 13:17
Ok, I get the same error when using 'Run as JUnit Test' but for some reason it works when I use 'Run as JUnit Plug-in Test'. However, some Tests fail.

I am quite sure the problem is caused by the difference dependency definitions in the Gradle and Eclipse configuration.
The following screenshot illustrates the problem. The 'Target Platform State' on the right-hand side shows the dependencies resolved by Eclipse from the Oomph definition. On the left-hand side the project dependencies point to jars in the gradle cache and not the Eclipse p2 pool.
Note that Gradle uses JUnit 5.6 and the Eclipse target platform version 5.7, this also affects the version of org.junit.platform. Even the Xtext versions differ: 2.14 vs. 2.15.
![dependnecies](https://user-images.githubusercontent.com/25612037/111030694-009da880-8404-11eb-942a-92e73cd347d4.png)

According to [StackOverflow](https://stackoverflow.com/a/64384746) the class org/junit/platform/commons/util/ClassNamePatternFilterUtils is introduced in version 1.7 of org.junit.platform. My guess is that Eclipse uses the target platform to compile the test plugin using version 1.7 but for some reason uses gradle dependencies to run it (maybe only in 'Run as JUnit Test' mode) which only provides version 1.6, hence the NoClassDefFoundError.

We either need to make Eclipse unaware of the differing versions in the Gradle configuration (as it was before using Oomph which installed Gradle support in Eclipse). This would fix the problem of mixing dependency definitions but could also result in situations where developers can compile code locally with Eclipse that will fail when using Gradle (e.g. in CI). Or we need a common target platform definition for Eclipse and Gradle but at the moment I do not know how to achive this. In my other Eclipse projects, we only used Maven which has the tycho plugin that is able to import the target definition from Oomph.

**Comment by lhstrh** [comment] 2021-03-14 06:56
Thanks for having a look at this, @a-sr! This suggest that the quick fix would be to bring the version numbers in compliance, but in the longer term we should make sure the dependencies are defined in just one place. Perhaps this project offers a viable solution: https://github.com/diffplug/goomph The idea would be that we generate the Oomph config from Gradle rather than configure it manually. WDYT?

**Comment by a-sr** [comment] 2021-03-23 12:36
I had a look at goomph and it is definitely promising. It may be even easier than the current installation via Oomph, if you only have to clone the repo and start one gradle command to create your development IDE.
I am not sure if it fully solves our problem because Eclipse still uses p2 update sites to install its features while gradle collects the plugins from MavenCentral. Hence, if an update site is able to smuggle a more recent version into the Eclipse installation and Eclipse uses this for compiling plugins, we might end up with the same problem. But at least we then have all the configuration in one place and can use common variables for the versions of xtext, junit, etc, in both p2 and gradle dependencies.
@lhstrh We should definitely try this out.

**Comment by lhstrh** [comment] 2021-03-30 22:49
They do work now. It appears that a fresh install also synchronizes with the Gradle configuration. The only point of contention still is that we essentially have two different places in which we declare dependencies. I will close this issue and create a new issue to address dependency management.

**Closed by lhstrh** 2021-03-30 22:49 UTC
