### ISSUE TITLE
Delay in action and schedule

### ISSUE THREAD

**Issue by schoeberl** [icyphy/lingua-franca#50] opened 2019-11-12 19:34 UTC
An action can have a mindelay as parameters and it can be scheduled with a delay in the schedule function. What is the relation between those? If both are set is the delay then the sum of both or the maximum of both? The current behavior is sum (plus the "error" below).

When using a mindelay in an action then the actual behavior is that the action is scheduled in double the time of the mindelay. Which is not "really" wrong, as the description states "minimum delay". But it feels wrong. What about being able to set the exact logical time delay?

**Comment by edwardalee** [comment] 2019-11-12 19:52
The reason is that minimum delay is useful for scheduling and
schedulability analysis.

Doubling of the delay is a bug. Do you have a test case?

Edward

------------
Edward A Lee
Professor
UC Berkeley

On Nov 12, 2019, at 11:34 AM, Martin Schoeberl <notifications@github.com>
wrote:

An action can have a mindelay as parameters and it can be scheduled with a
delay in the schedule function. What is the relation between those? If both
are set is the delay then the sum of both or the maximum of both? The
current behavior is sum (plus the "error" below).

When using a mindelay in an action then the actual behavior is that the
action is scheduled in double the time of the mindelay. Which is not
"really" wrong, as the description states "minimum delay". But it feels
wrong. What about being able to set the exact logical time delay?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/icyphy/lingua-franca/issues/50?email_source=notifications&email_token=ACA6ONWCJFYS6S23A3KFAC3QTMAL3A5CNFSM4JMIABBKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HYZMQWA>,
or unsubscribe

**Comment by schoeberl** [comment] 2019-11-12 21:26
Now there is a test case: xtext/org.icyphy.linguafranca/src/test/C/ActionDelay.lf

Are schedule delays and action delays added or maxed? What is the effective delay of:

```
physical action act(100 msec);
...
schedule(act, MSEC(200), NULL);
```
200 or 300 ms?

Martin

**Comment by edwardalee** [comment] 2019-11-12 21:37
I see that the wiki is not very clear in the language specification.
I always assumed the delays would be added. The name of the parameter to the schedule() function is “extra_delay”,
which implies they should be added.
We should fix the wiki to be clear about this.

Edward

———————
Edward A. Lee
Professor of the Graduate School
EECS, UC Berkeley
http://eecs.berkeley.edu/~eal

**Comment by schoeberl** [comment] 2019-11-12 21:58
Gave the Wiki description a shot. Note that I removed the term "mindelay", as this was partially confusing for me. But I added a sentence that the action delay can be seen as a minimum delay for schedulability analysis. Maybe you can check if you agree with my words.

**Comment by edwardalee** [comment] 2019-11-13 02:01
I’ve pushed a fix. The C code in the schedule() function was wrong.
I added a version of your test to the regression tests.
I changed the action to be a logical one rather than a physical one.
I think if it’s physical, then we can’t actually rely on the results coming out right.
Perhaps it is a coincidence that they do.

Edward

——————
Edward A. Lee
Professor of the Graduate School
EECS, UC Berkeley
http://eecs.berkeley.edu/~eal

**Comment by schoeberl** [comment] 2019-11-13 05:30
Great, thanks! When I get my Eclipse to sync again, I can use it for the reaction/after delay.

Mmh, I think I need to better understand the physical/logic action delay.
So the reaction delay with “after” should use a logical time delay?
Maybe we can recap this tomorrow.

Cheers,
Maartin

**Comment by lhstrh** [comment] 2019-11-13 05:55
Yes, `after` should use a logical delay. What this means is that the event
will be scheduled relative to the current logical time (as opposed to the
current physical time).

**Closed** 2019-11-15 14:46 UTC
